spring.application.name=SmartBill360
springdoc.swagger-ui.path=/apidocs.html

spring.datasource.url=jdbc:mysql://localhost:3306/smartbill360
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=root
spring.datasource.password=root

secret_key = f7b1f947bda24255a48671cf9e8d0847f7b1f947bda24255a


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mehul.vv19@gmail.com
spring.mail.password=kgro pmre rahj jykb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true